### ISSUE TITLE
Error when accessing "new video" page

### ISSUE THREAD

**Issue by DavidArutiunian** [DavidArutiunian/video-server#1]
Some `isoPartialView` class not found
```
[Mon Feb 19 15:00:21 2018] PHP Fatal error:  Uncaught Error: Class 'isoPartialView' not found in C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php:215
Stack trace:
#0 C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php(180): get_partial('form', Array)
#1 C:\Users\DavidOS\PhpstormProjects\video-server\apps\frontend\modules\videofile\templates\newSuccess.php(5): include_partial('form', Array)
#2 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(3821): require('C:\\Users\\DavidO...')
#3 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(3876): sfPHPView->renderFile('C:\\Users\\DavidO...')
#4 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(971): sfPHPView->render()
#5 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(958): sfExecutionFilter->executeView( in C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php on line 215
[Mon Feb 19 15:00:21 2018] 127.0.0.1:30799 [500]: /videofile/new - Uncaught Error: Class 'isoPartialView' not found in C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php:215
Stack trace:
#0 C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php(180): get_partial('form', Array)
#1 C:\Users\DavidOS\PhpstormProjects\video-server\apps\frontend\modules\videofile\templates\newSuccess.php(5): include_partial('form', Array)
#2 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(3821): require('C:\\Users\\DavidO...')
#3 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(3876): sfPHPView->renderFile('C:\\Users\\DavidO...')
#4 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(971): sfPHPView->render()
#5 C:\Users\DavidOS\PhpstormProjects\video-server\cache\frontend\prod\config\config_core_compile.yml.php(958): sfExecutionFilter->executeView( in C:\Users\DavidOS\PhpstormProjects\video-server\vendor\vadimdol\symfony1\lib\helper\PartialHelper.php on line 215
```

**Comment by DavidArutiunian** [comment]
Should add these lines to **ProjectConfiguration.class.php**
``` php
    public function setup()
    {
        $this->enablePlugins('sfPropelPlugin');
        $this->enablePlugins('isoOptimizerPlugin');
        $this->enablePlugins('isoCommonPartialPlugin');
    }
```
